spring:
  config:
    activate:
      on-profile: test
  datasource:
    url:  jdbc:h2:mem:testdb
    username: root
    password: dante123
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
server:
  port: 6000